name: first simple project
on: [push,workflow_dispatch]
jobs:
  first-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "good morning"
      - name: print good bye
        run: |
          echo "bye bye"
          ls -lrt
          cat /proc/version
          cat /etc/os-release
      - name: output of github context
        run: echo "&{{github}}"
