name: Main yaml
on: [push,workflow_dispatch]
jobs:
  Prepare_Task:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{steps.repo_branch.outputs.branch_name}}
      version_name: ${{steps.version_name.outputs.version_name}}
    steps:
      - id: repo_branch
        run: echo "${{github.ref.name}}" >>GITHUB_OUTPUT
      - id: version_name
        run: echo "version=1.2.5">>GITHUB_OUTPUT
  call-reusable:
    needs: Prepare_Task
    uses: sh378269/first-project/.github/workflows/reusable.yml@Output-test
    with:
      branch: ${{needs.Prepare_Task.ouputs.branch_name}}
      version: ${{needs.Prepare_Task.output.version_name}}
      repo_name: ${{github.event.repositor.name}}
    secrets:
      test_passwrd: ${{secrets.testpswrd}}
