name: Main yaml
on: [push,workflow_dispatch]
jobs:
  Prepare_Task:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{steps.repo_branch.outputs.branch_name}}
      version_name: ${{steps.version_name.outputs.version_name}}
    steps:
      - id: repo_branch
        run: echo "${{github.ref.name}}" >>GITHUB_OUTPUT
      - id: version_name
        run: echo "version=1.2.5">>GITHUB_OUTPUT
      # - name: print GITHUB output
      #   run: echo "${{GITHUB_OUTPUT.repo_branch}}"